// Generates the C# GDExtension interface layer from Godot's machine-readable
// interface description (core/extension/gdextension_interface.json) - the same
// file the engine uses to generate gdextension_interface.gen.h. No ClangSharp,
// no header parsing.
//
// Usage:
//   dotnet run --project twodog.bindings.generator -- <gdextension_interface.json> <output.gen.cs>

using System.Text;
using System.Text.Json;

if (args.Length == 3 && args[0] == "api")
{
    twodog.bindings.generator.ApiGenerator.Run(args[1], args[2]);
    return 0;
}

if (args.Length != 2)
{
    Console.Error.WriteLine("usage: twodog.bindings.generator <gdextension_interface.json> <output.gen.cs>");
    Console.Error.WriteLine("       twodog.bindings.generator api <extension_api.json> <output-dir>");
    return 1;
}

var doc = JsonDocument.Parse(File.ReadAllText(args[0]));
var root = doc.RootElement;

var types = root.GetProperty("types").EnumerateArray().ToDictionary(t => t.GetProperty("name").GetString()!);
var interfaceFns = root.GetProperty("interface").EnumerateArray().ToArray();

// ---- type mapping ---------------------------------------------------------

var aliases = new Dictionary<string, string>();
foreach (var (name, t) in types)
    if (Kind(t) == "alias")
        aliases[name] = t.GetProperty("type").GetString()!;

string Kind(JsonElement t) => t.GetProperty("kind").GetString()!;

string MapType(string c)
{
    c = c.Replace("const ", "").Trim();
    if (c.EndsWith('*')) return "nint";                    // all pointers are opaque to this layer
    while (aliases.TryGetValue(c, out var target)) c = target;
    if (types.TryGetValue(c, out var t))
    {
        return Kind(t) switch
        {
            "enum" => "int",                               // enums pass as int in signatures
            "handle" => "nint",
            "function" => "nint",                          // callbacks pass as raw fn pointers
            "struct" => c,                                 // by-value struct (rare)
            _ => "nint",
        };
    }
    return c switch
    {
        "void" => "void",
        "char32_t" => "uint",
        "wchar_t" => "ushort",
        "uint8_t" => "byte",
        "int8_t" => "sbyte",
        "uint16_t" => "ushort",
        "int16_t" => "short",
        "uint32_t" => "uint",
        "int32_t" => "int",
        "uint64_t" => "ulong",
        "int64_t" => "long",
        "size_t" => "nuint",
        "float" => "float",
        "double" => "double",
        _ => Fail($"unmapped C type: {c}"),
    };
}

string Fail(string message) => throw new InvalidOperationException(message);

var csharpKeywords = new HashSet<string>
{
    "string", "object", "base", "params", "event", "class", "struct", "enum", "interface",
    "ref", "out", "in", "int", "uint", "long", "ulong", "byte", "sbyte", "short", "ushort",
    "float", "double", "bool", "char", "void", "default", "operator", "lock", "fixed", "internal",
};

string Ident(string name) => csharpKeywords.Contains(name) ? "@" + name : name;

string Pascal(string snake) =>
    string.Concat(snake.Split('_', StringSplitOptions.RemoveEmptyEntries)
        .Select(w => char.ToUpperInvariant(w[0]) + w[1..]));

string FnPointerType(JsonElement fn)
{
    var argTypes = fn.TryGetProperty("arguments", out var fnArgs)
        ? fnArgs.EnumerateArray().Select(a => MapType(a.GetProperty("type").GetString()!)).ToList()
        : [];
    var ret = fn.TryGetProperty("return_value", out var rv)
        ? MapType(rv.GetProperty("type").GetString()!)
        : "void";
    argTypes.Add(ret);
    return $"delegate* unmanaged<{string.Join(", ", argTypes)}>";
}

// ---- emit -----------------------------------------------------------------

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated>");
sb.AppendLine("// Generated by twodog.bindings.generator from gdextension_interface.json.");
sb.AppendLine($"// Interface functions: {interfaceFns.Length} total, {interfaceFns.Count(f => f.TryGetProperty("deprecated", out _))} deprecated (skipped).");
sb.AppendLine("// Do not edit by hand - regenerate instead.");
sb.AppendLine("// </auto-generated>");
sb.AppendLine();
sb.AppendLine("// ReSharper disable All");
sb.AppendLine("#pragma warning disable CS8618, CA1069");
sb.AppendLine();
sb.AppendLine("using System.Runtime.InteropServices;");
sb.AppendLine();
sb.AppendLine("namespace Godot.NativeInterop;");
sb.AppendLine();

// enums
foreach (var (name, t) in types)
{
    if (Kind(t) != "enum") continue;
    sb.AppendLine($"public enum {name}");
    sb.AppendLine("{");
    foreach (var v in t.GetProperty("values").EnumerateArray())
        sb.AppendLine($"    {v.GetProperty("name").GetString()} = {v.GetProperty("value").GetInt64()},");
    sb.AppendLine("}");
    sb.AppendLine();
}

// structs (skip pure aliases like CreationInfo5 -> CreationInfo4)
foreach (var (name, t) in types)
{
    if (Kind(t) != "struct") continue;
    sb.AppendLine("[StructLayout(LayoutKind.Sequential)]");
    sb.AppendLine($"public struct {name}");
    sb.AppendLine("{");
    foreach (var m in t.GetProperty("members").EnumerateArray())
    {
        var mapped = MapType(m.GetProperty("type").GetString()!);
        if (mapped == "int" && types.TryGetValue(m.GetProperty("type").GetString()!.Replace("const ", "").Trim(), out var mt) && Kind(mt) == "enum")
            mapped = m.GetProperty("type").GetString()!; // struct fields keep real enum types
        sb.AppendLine($"    public {mapped} {Ident(m.GetProperty("name").GetString()!)};");
    }
    sb.AppendLine("}");
    sb.AppendLine();
}

// interface loader
sb.AppendLine("/// <summary>");
sb.AppendLine("/// The raw GDExtension interface: one typed function pointer per proc,");
sb.AppendLine("/// resolved by name via get_proc_address at initialization time.");
sb.AppendLine("/// </summary>");
sb.AppendLine("public static unsafe class GdExtensionInterface");
sb.AppendLine("{");

var loaded = new List<(string field, string procName, string fpType)>();
foreach (var fn in interfaceFns)
{
    if (fn.TryGetProperty("deprecated", out _)) continue;
    var procName = fn.GetProperty("name").GetString()!;
    var field = Pascal(procName);
    var fpType = FnPointerType(fn);
    loaded.Add((field, procName, fpType));
    sb.AppendLine($"    public static {fpType} {field};");
}

sb.AppendLine();
sb.AppendLine("    /// <summary>Procs requested but not found in this engine build (empty on success).</summary>");
sb.AppendLine("    public static readonly List<string> MissingProcs = [];");
sb.AppendLine();
sb.AppendLine("    public static void Load(nint getProcAddress)");
sb.AppendLine("    {");
sb.AppendLine("        var gpa = (delegate* unmanaged<nint, nint>)getProcAddress;");
foreach (var (field, procName, fpType) in loaded)
    sb.AppendLine($"        {field} = ({fpType})Get(gpa, \"{procName}\"u8);");
sb.AppendLine("    }");
sb.AppendLine();
sb.AppendLine("    private static nint Get(delegate* unmanaged<nint, nint> gpa, ReadOnlySpan<byte> name)");
sb.AppendLine("    {");
sb.AppendLine("        Span<byte> zt = stackalloc byte[name.Length + 1];");
sb.AppendLine("        name.CopyTo(zt);");
sb.AppendLine("        zt[name.Length] = 0;");
sb.AppendLine("        fixed (byte* p = zt)");
sb.AppendLine("        {");
sb.AppendLine("            var fn = gpa((nint)p);");
sb.AppendLine("            if (fn == 0) MissingProcs.Add(System.Text.Encoding.ASCII.GetString(name));");
sb.AppendLine("            return fn;");
sb.AppendLine("        }");
sb.AppendLine("    }");
sb.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(args[1]))!);
File.WriteAllText(args[1], sb.ToString());
Console.WriteLine($"Generated {args[1]}: {loaded.Count} procs, " +
                  $"{types.Values.Count(t => Kind(t) == "enum")} enums, " +
                  $"{types.Values.Count(t => Kind(t) == "struct")} structs.");
return 0;
