using Avalonia.Input;
using AvaloniaKey = Avalonia.Input.Key;
using GodotKey = Godot.Key;

namespace twodog;

/// <summary>Maps Avalonia input enums to their Godot counterparts.</summary>
internal static class KeyMap
{
    /// <summary>Logical key (layout-dependent). OEM keys assume their US-layout meaning,
    /// matching how Avalonia itself derives them from virtual-key codes. The physical key
    /// disambiguates logical values Avalonia aliases (KanaMode/HangulMode).</summary>
    public static GodotKey ToKeycode(AvaloniaKey key, PhysicalKey physical) => key switch
    {
        >= AvaloniaKey.A and <= AvaloniaKey.Z => GodotKey.A + (key - AvaloniaKey.A),
        >= AvaloniaKey.D0 and <= AvaloniaKey.D9 => GodotKey.Key0 + (key - AvaloniaKey.D0),
        >= AvaloniaKey.NumPad0 and <= AvaloniaKey.NumPad9 => GodotKey.Kp0 + (key - AvaloniaKey.NumPad0),
        >= AvaloniaKey.F1 and <= AvaloniaKey.F24 => GodotKey.F1 + (key - AvaloniaKey.F1),
        AvaloniaKey.Return => GodotKey.Enter,
        AvaloniaKey.Escape => GodotKey.Escape,
        AvaloniaKey.Tab => GodotKey.Tab,
        AvaloniaKey.Back => GodotKey.Backspace,
        AvaloniaKey.Clear or AvaloniaKey.OemClear => GodotKey.Clear,
        // KanaMode aliases HangulMode (both 9); only an actual JIS kana key reads as such.
        // Godot has no Hangul keycode, so the Korean toggle stays Unknown (its physical
        // keycode still identifies it) instead of masquerading as kana.
        AvaloniaKey.KanaMode when physical == PhysicalKey.KanaMode => GodotKey.JisKana,
        AvaloniaKey.Space => GodotKey.Space,
        AvaloniaKey.PageUp => GodotKey.Pageup,
        AvaloniaKey.PageDown => GodotKey.Pagedown,
        AvaloniaKey.End => GodotKey.End,
        AvaloniaKey.Home => GodotKey.Home,
        AvaloniaKey.Left => GodotKey.Left,
        AvaloniaKey.Up => GodotKey.Up,
        AvaloniaKey.Right => GodotKey.Right,
        AvaloniaKey.Down => GodotKey.Down,
        AvaloniaKey.Insert => GodotKey.Insert,
        AvaloniaKey.Delete => GodotKey.Delete,
        AvaloniaKey.Help => GodotKey.Help,
        AvaloniaKey.Pause => GodotKey.Pause,
        AvaloniaKey.CapsLock => GodotKey.Capslock,
        AvaloniaKey.NumLock => GodotKey.Numlock,
        AvaloniaKey.Scroll => GodotKey.Scrolllock,
        AvaloniaKey.PrintScreen or AvaloniaKey.Print => GodotKey.Print,
        AvaloniaKey.LWin or AvaloniaKey.RWin => GodotKey.Meta,
        AvaloniaKey.Apps => GodotKey.Menu,
        AvaloniaKey.Sleep => GodotKey.Standby,
        AvaloniaKey.LeftShift or AvaloniaKey.RightShift => GodotKey.Shift,
        AvaloniaKey.LeftCtrl or AvaloniaKey.RightCtrl => GodotKey.Ctrl,
        AvaloniaKey.LeftAlt or AvaloniaKey.RightAlt => GodotKey.Alt,
        AvaloniaKey.Multiply => GodotKey.KpMultiply,
        AvaloniaKey.Add => GodotKey.KpAdd,
        AvaloniaKey.Subtract => GodotKey.KpSubtract,
        AvaloniaKey.Divide => GodotKey.KpDivide,
        AvaloniaKey.Decimal => GodotKey.KpPeriod,
        // The keypad separator (locale-dependent comma/period); Godot's nearest keypad
        // key, matching the physical NumPadComma mapping.
        AvaloniaKey.Separator => GodotKey.KpPeriod,
        AvaloniaKey.BrowserBack => GodotKey.Back,
        AvaloniaKey.BrowserForward => GodotKey.Forward,
        AvaloniaKey.BrowserRefresh => GodotKey.Refresh,
        AvaloniaKey.BrowserStop => GodotKey.Stop,
        AvaloniaKey.BrowserSearch => GodotKey.Search,
        AvaloniaKey.BrowserFavorites => GodotKey.Favorites,
        AvaloniaKey.BrowserHome => GodotKey.Homepage,
        AvaloniaKey.VolumeMute => GodotKey.Volumemute,
        AvaloniaKey.VolumeDown => GodotKey.Volumedown,
        AvaloniaKey.VolumeUp => GodotKey.Volumeup,
        AvaloniaKey.MediaNextTrack => GodotKey.Medianext,
        AvaloniaKey.MediaPreviousTrack => GodotKey.Mediaprevious,
        AvaloniaKey.MediaStop => GodotKey.Mediastop,
        AvaloniaKey.MediaPlayPause => GodotKey.Mediaplay,
        AvaloniaKey.LaunchMail => GodotKey.Launchmail,
        AvaloniaKey.SelectMedia => GodotKey.Launchmedia,
        AvaloniaKey.LaunchApplication1 => GodotKey.Launch0,
        AvaloniaKey.LaunchApplication2 => GodotKey.Launch1,
        AvaloniaKey.OemSemicolon => GodotKey.Semicolon,
        AvaloniaKey.OemPlus => GodotKey.Equal,
        AvaloniaKey.OemComma => GodotKey.Comma,
        AvaloniaKey.OemMinus => GodotKey.Minus,
        AvaloniaKey.OemPeriod => GodotKey.Period,
        AvaloniaKey.OemQuestion => GodotKey.Slash,
        AvaloniaKey.OemTilde => GodotKey.Quoteleft,
        AvaloniaKey.OemOpenBrackets => GodotKey.Bracketleft,
        AvaloniaKey.OemPipe => GodotKey.Backslash,
        AvaloniaKey.OemCloseBrackets => GodotKey.Bracketright,
        AvaloniaKey.OemQuotes => GodotKey.Apostrophe,
        AvaloniaKey.OemBackslash => GodotKey.Backslash,
        _ => GodotKey.Unknown,
    };

    /// <summary>Physical key (layout-independent, keyboard position).</summary>
    public static GodotKey ToPhysicalKeycode(PhysicalKey key) => key switch
    {
        >= PhysicalKey.A and <= PhysicalKey.Z => GodotKey.A + (key - PhysicalKey.A),
        >= PhysicalKey.Digit0 and <= PhysicalKey.Digit9 => GodotKey.Key0 + (key - PhysicalKey.Digit0),
        >= PhysicalKey.NumPad0 and <= PhysicalKey.NumPad9 => GodotKey.Kp0 + (key - PhysicalKey.NumPad0),
        >= PhysicalKey.F1 and <= PhysicalKey.F24 => GodotKey.F1 + (key - PhysicalKey.F1),
        PhysicalKey.Backquote => GodotKey.Quoteleft,
        PhysicalKey.Backslash or PhysicalKey.IntlBackslash => GodotKey.Backslash,
        PhysicalKey.BracketLeft => GodotKey.Bracketleft,
        PhysicalKey.BracketRight => GodotKey.Bracketright,
        PhysicalKey.Comma => GodotKey.Comma,
        PhysicalKey.Equal => GodotKey.Equal,
        PhysicalKey.IntlYen => GodotKey.Yen,
        PhysicalKey.Minus => GodotKey.Minus,
        PhysicalKey.Period => GodotKey.Period,
        PhysicalKey.Quote => GodotKey.Apostrophe,
        PhysicalKey.Semicolon => GodotKey.Semicolon,
        PhysicalKey.Slash => GodotKey.Slash,
        PhysicalKey.AltLeft or PhysicalKey.AltRight => GodotKey.Alt,
        PhysicalKey.Backspace => GodotKey.Backspace,
        PhysicalKey.CapsLock => GodotKey.Capslock,
        PhysicalKey.ContextMenu => GodotKey.Menu,
        PhysicalKey.ControlLeft or PhysicalKey.ControlRight => GodotKey.Ctrl,
        PhysicalKey.Enter => GodotKey.Enter,
        PhysicalKey.MetaLeft or PhysicalKey.MetaRight => GodotKey.Meta,
        PhysicalKey.ShiftLeft or PhysicalKey.ShiftRight => GodotKey.Shift,
        PhysicalKey.Space => GodotKey.Space,
        PhysicalKey.Tab => GodotKey.Tab,
        PhysicalKey.KanaMode => GodotKey.JisKana,
        PhysicalKey.Delete => GodotKey.Delete,
        PhysicalKey.End => GodotKey.End,
        PhysicalKey.Help => GodotKey.Help,
        PhysicalKey.Home => GodotKey.Home,
        PhysicalKey.Insert => GodotKey.Insert,
        PhysicalKey.PageDown => GodotKey.Pagedown,
        PhysicalKey.PageUp => GodotKey.Pageup,
        PhysicalKey.ArrowDown => GodotKey.Down,
        PhysicalKey.ArrowLeft => GodotKey.Left,
        PhysicalKey.ArrowRight => GodotKey.Right,
        PhysicalKey.ArrowUp => GodotKey.Up,
        PhysicalKey.NumLock => GodotKey.Numlock,
        PhysicalKey.NumPadAdd => GodotKey.KpAdd,
        PhysicalKey.NumPadClear => GodotKey.Clear,
        PhysicalKey.NumPadComma or PhysicalKey.NumPadDecimal => GodotKey.KpPeriod,
        PhysicalKey.NumPadDivide => GodotKey.KpDivide,
        PhysicalKey.NumPadEnter => GodotKey.KpEnter,
        PhysicalKey.NumPadEqual => GodotKey.Equal,
        PhysicalKey.NumPadMultiply => GodotKey.KpMultiply,
        PhysicalKey.NumPadParenLeft => GodotKey.Parenleft,
        PhysicalKey.NumPadParenRight => GodotKey.Parenright,
        PhysicalKey.NumPadSubtract => GodotKey.KpSubtract,
        PhysicalKey.Escape => GodotKey.Escape,
        PhysicalKey.PrintScreen => GodotKey.Print,
        PhysicalKey.ScrollLock => GodotKey.Scrolllock,
        PhysicalKey.Pause => GodotKey.Pause,
        PhysicalKey.BrowserBack => GodotKey.Back,
        PhysicalKey.BrowserFavorites => GodotKey.Favorites,
        PhysicalKey.BrowserForward => GodotKey.Forward,
        PhysicalKey.BrowserHome => GodotKey.Homepage,
        PhysicalKey.BrowserRefresh => GodotKey.Refresh,
        PhysicalKey.BrowserSearch => GodotKey.Search,
        PhysicalKey.BrowserStop => GodotKey.Stop,
        PhysicalKey.LaunchApp1 => GodotKey.Launch0,
        PhysicalKey.LaunchApp2 => GodotKey.Launch1,
        PhysicalKey.LaunchMail => GodotKey.Launchmail,
        PhysicalKey.MediaPlayPause => GodotKey.Mediaplay,
        PhysicalKey.MediaSelect => GodotKey.Launchmedia,
        PhysicalKey.MediaStop => GodotKey.Mediastop,
        PhysicalKey.MediaTrackNext => GodotKey.Medianext,
        PhysicalKey.MediaTrackPrevious => GodotKey.Mediaprevious,
        PhysicalKey.Sleep => GodotKey.Standby,
        PhysicalKey.AudioVolumeDown => GodotKey.Volumedown,
        PhysicalKey.AudioVolumeMute => GodotKey.Volumemute,
        PhysicalKey.AudioVolumeUp => GodotKey.Volumeup,
        _ => GodotKey.Unknown,
    };

    /// <summary>The button a pointer press/release transition refers to; None for moves.</summary>
    public static Godot.MouseButton ToMouseButton(PointerUpdateKind kind) => kind switch
    {
        PointerUpdateKind.LeftButtonPressed or PointerUpdateKind.LeftButtonReleased => Godot.MouseButton.Left,
        PointerUpdateKind.RightButtonPressed or PointerUpdateKind.RightButtonReleased => Godot.MouseButton.Right,
        PointerUpdateKind.MiddleButtonPressed or PointerUpdateKind.MiddleButtonReleased => Godot.MouseButton.Middle,
        PointerUpdateKind.XButton1Pressed or PointerUpdateKind.XButton1Released => Godot.MouseButton.Xbutton1,
        PointerUpdateKind.XButton2Pressed or PointerUpdateKind.XButton2Released => Godot.MouseButton.Xbutton2,
        _ => Godot.MouseButton.None,
    };

    public static Godot.MouseButtonMask ToMask(Godot.MouseButton button) => button switch
    {
        Godot.MouseButton.Left => Godot.MouseButtonMask.Left,
        Godot.MouseButton.Right => Godot.MouseButtonMask.Right,
        Godot.MouseButton.Middle => Godot.MouseButtonMask.Middle,
        Godot.MouseButton.Xbutton1 => Godot.MouseButtonMask.MbXbutton1,
        Godot.MouseButton.Xbutton2 => Godot.MouseButtonMask.MbXbutton2,
        _ => 0,
    };
}
