<Project Sdk="Godot.NET.Sdk/4.7.2">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <IsTrimmable>false</IsTrimmable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="2dog.godotsharp" Version="$(TwoDogVersion)"/>
    </ItemGroup>
</Project>
