#!/usr/bin/env python3
"""Generate twodog.bindings/Generated/WebTrampolines.gen.cs.

The mono-wasm build only emits interpreter-to-native trampolines for
signatures it can see on [UnmanagedFunctionPointer] delegate declarations -
`delegate* unmanaged<...>` call sites are invisible to its scanner. This
script scans the gdext stack for every such function-pointer type, reduces
each to its wasm signature shape (i32/i64/f32/f64/void), and emits one
representative delegate per distinct shape.

Re-run after regenerating the bindings or adding fnptr interop:
    python scripts/gen_web_trampolines.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCAN_DIRS = [REPO / "twodog.bindings", REPO / "twodog.gdextension"]
OUT = REPO / "twodog.bindings" / "Generated" / "WebTrampolines.gen.cs"

FNPTR_RE = re.compile(r"delegate\*\s*unmanaged(?:\[[^\]]*\])?\s*<(.*?)>", re.DOTALL)

# wasm value-type shape codes.
I32, I64, F32, F64, VOID = "i", "l", "f", "d", "v"

SHAPE_TO_CS = {I32: "IntPtr", I64: "long", F32: "float", F64: "double", VOID: "void"}


def shape_of(cs_type: str) -> str:
    t = cs_type.strip()
    if t == "void":
        return VOID
    if t.endswith("*") or t in ("nint", "nuint", "IntPtr", "UIntPtr"):
        return I32
    if t in ("long", "ulong"):
        return I64
    if t == "float":
        return F32
    if t == "double":
        return F64
    # int, uint, byte, sbyte, short, ushort, char, bool and enums are i32.
    return I32


def split_types(type_list: str) -> list[str]:
    # Function-pointer type lists never nest generics; a plain comma split
    # works. Normalize whitespace (declarations may span lines).
    return [" ".join(part.split()) for part in type_list.split(",")]


def main() -> int:
    shapes: set[tuple[str, tuple[str, ...]]] = set()
    for scan_dir in SCAN_DIRS:
        for path in scan_dir.rglob("*.cs"):
            if path.name == OUT.name:
                continue
            for match in FNPTR_RE.finditer(path.read_text(encoding="utf-8")):
                types = split_types(match.group(1))
                ret = shape_of(types[-1])
                args = tuple(shape_of(t) for t in types[:-1])
                shapes.add((ret, args))

    lines = [
        "// Generated by scripts/gen_web_trampolines.py - do not edit.",
        "//",
        "// Forces the mono wasm build to generate interpreter trampolines for",
        "// every function-pointer signature shape the gdext stack calls through",
        "// (delegate* unmanaged call sites are invisible to its scanner).",
        "// Only the declarations matter; nothing instantiates these.",
        "using System;",
        "using System.Runtime.InteropServices;",
        "",
        "namespace Godot.NativeInterop;",
        "",
        "internal static class WebTrampolines",
        "{",
    ]
    for ret, args in sorted(shapes):
        name = f"sig_{ret}_{''.join(args) or 'void'}"
        params = ", ".join(f"{SHAPE_TO_CS[a]} _{i}" for i, a in enumerate(args))
        lines.append("    [UnmanagedFunctionPointer(CallingConvention.Winapi)]")
        lines.append(f"    internal delegate {SHAPE_TO_CS[ret]} {name}({params});")
    lines.append("}")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"{OUT.relative_to(REPO)}: {len(shapes)} signature shapes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
